name: fcm-example
services:
  backend:
    build: .devcontainer/backend/
    env_file:
      - ./backend/.env
    tty: true
    volumes:
      - backend-data:/home/bouzuya/app/backend/target
      - .:/home/bouzuya/app
  frontend:
    depends_on:
      - backend
    image: node:22.12.0-bookworm
    tty: true
    volumes:
      - frontend-data:/app/frontend/node_modules
      - .:/app
volumes:
  backend-data:
  frontend-data:
