name: fcm-example
services:
  backend:
    build: .devcontainer/backend/
    env_file:
      - ./backend/.env
    tty: true
    volumes:
      - .:/home/bouzuya/app
  frontend:
    build: .devcontainer/frontend/
    tty: true
    volumes:
      - .:/home/bouzuya/app
