name: fcm-example
services:
  backend:
    build: .devcontainer/backend/
    env_file:
      - ./backend/.env
    tty: true
    volumes:
      - .:/home/bouzuya/app
  frontend:
    depends_on:
      - backend
    image: node:22.12.0-bookworm
    tty: true
    volumes:
      - .:/app
